server.port: ${PORT:8080}

app:
  link:
    login: https://ptrvsky.github.io/zpi-frontend/#/login
  security:
    secret: LUKASZHEHEHEHE
  mail:
    apikey:
    from: wroclavbestpizza@gmail.com
    images:
      pizzaLeft: https://burdzi0.github.io/images/pizza_left.jpg
      pizzaRight: https://burdzi0.github.io/images/pizza_right.jpg
      title: https://burdzi0.github.io/images/title.png
  heroku:
    url: https://pizzeria-backend-zpi.herokuapp.com

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
